### ISSUE TITLE
Hue Switch not responding...

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#768] opened 2020-09-19 11:00 UTC
#### Issue
Hi,
since updating to the latest release of homebridge (1.2.2) my Hue switches are making problems (Hue Dimmer and Hue Tap switch).

Behavior:
They are working (connected to HomeKit via homebridge and not directly to the Hue bridge) for some hours, and then they stop working immediately...

Solution is to restart homebridge to get them up and running for the next hours until I have to restart again...

If I press a button on a Hue switch I can see an log entry on homebridge that a button was pressed but the configured lights do nothing.

#### Log Messages
[9/19/2020, 12:19:59 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:00 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:01 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:04 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:06 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:34 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:35 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:36 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:37 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:39 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:45 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:47 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER Dim Up: homekit button single press
[9/19/2020, 12:20:48 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press
[9/19/2020, 12:20:52 PM] [Homebridge-Hue] Hue Dimmer WOHNZIMMER On: homekit button single press

Config (not changed, works before with the same settings):
{
            "name": "Homebridge-Hue",
            "anyOn": true,
            "excludeSensorTypes": [
                "ZLLRelativeRotary",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "ZHAOpenClose",
                "ZHAAlarm",
                "ZHACarbonMonoxide",
                "ZHAFire",
                "ZHAVibration",
                "ZHAWater",
                "ZHAConsumption",
                "ZHAPower",
                "ZHAThermostat",
                "Daylight",
                "CLIPGenericFlag",
                "CLIPGenericStatus",
                "CLIPPresence",
                "CLIPLightLevel",
                "CLIPTemperature",
                "CLIPHumidity",
                "CLIPPressure",
                "CLIPOpenClose",
                "CLIPAlarm",
                "CLIPCarbonMonoxide",
                "CLIPFire",
                "CLIPVibration",
                "CLIPWater",
                "CLIPConsumption",
                "CLIPPower",
                "Geofence",
                "CLIP"
            ],
            "forceCt": true,
            "heartrate": 1,
            "hosts": [
                "192.168.0.50"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "users": {
                "xxxxx": "xxxxx"
            },
            "platform": "Hue"

Any ideas what I can do to get the switches back stable again?

Thanks JO!

**Comment by ebaauw** [comment] 2020-09-19 11:23
> If I press a button on a Hue switch I can see an log entry on homebridge that a button was pressed

That means Homebridge Hue is doing its thing.

> since updating to the latest release of homebridge (1.2.2) my Hue switches are making problems (Hue Dimmer and Hue Tap switch).

Is that the only recent change you made?  Did you also recently update to iOS 14?  Did you change the setup of your home network (maybe switching from wired to wireless or adding a new WiFi access point)?

> but the configured lights do nothing.

Configured how?  Using associated groups (in deCONZ only), using Hue bridge/deCONZ gateway rules, using HomeKit automations (or actions assigned to the buttons in HomeKit)?  In case of the latter: this is probably an issue with your Home hub losing the connection to Homebridge.  What Home hub do you use?  Has it been updated to iPadOS 14 or tvOS 14?  I would expect issues with the HomePod, as updated firmware is not yet available.

> Solution is to restart homebridge to get them up and running for the next hours until I have to restart again...

Next time, try restarting the Home hub instead, to see if that also solves the issue.  Before that, check with `netstat` on the server running Homebridge, whether the Home hub still has an open connection to Homebridge.  If the connection between Home hub and Homebridge was indeed lost (and restored after restarting the Home hub), the issue is likely caused by mismatch in iOS versions between the hub and other HomeKit clients, by issues with `ciao` in Homebridge v1.2.2, or by issues in your home network (although you would have seen the issues in earlier versions of Homebridge).

**Comment by jostrasser** [comment] 2020-09-19 11:59
> Is that the only recent change you made? Did you also recently update to iOS 14? Did you change the setup of your home network (maybe switching from wired to wireless or adding a new WiFi access point)?

I haven't changed anything on my home network but have done an upgrade to iOS14 on my iPhones and upgraded to tvOS14 on my both Apple TVs which are the HomeKit bridges.

I have added the switches a long time ago to Apple Home and configured some Scenes in Apple Home and set them on the Switch buttons via the Home App.

The last times I have tested:
1) Restarting Hue Bridge -- does not solve the issue
2) Restarting HomeBridge -- solves the issue for some time
3) Restarting Apple TVs -- solves the issue for some time

From this perspective I think it can be a connectivity issue between my AppleTVs and homebridge... but I also run the last 4 beta releases without any issues. It occurs definitely after installing the GA release.

Next time I will check with netstat the opened connections...
What do you mean with "mismatch of iOS versions"? All devices are running on the latest iOS releases (tvOS, iOS, iPadOS).
Are there any known issues with iOS14 or Homebridge 1.2.2?

Thanks and BR/JO!

**Comment by ebaauw** [comment] 2020-09-19 12:12
> Are there any known issues with iOS14 or Homebridge 1.2.2?

I think I saw some mention of people having issues with HomePod, for which the iOS 14 equivalent version is not yet available.

For Homebridge 1.2.2 issues, see https://github.com/homebridge/homebridge/issues/2681.  I don’t experience these myself and it seems to be limited to less common setups, but they would explain the lost connection between the Home hub and HomeKit.

**Comment by jostrasser** [comment] 2020-09-19 17:18
Hi @ebaauw 
thanks for linking my issue to the homebridge issue.
Looks similar...

BR/JO!

**Comment by ebaauw** [comment] 2020-09-19 17:37
> Controlling lamps via the Home App is still working.

The Home hub plays no role there.

> BR/JO!

Not familiar with that (those?) abbreviation(s).  Asked my kid, but he doesn’t have a clue either.  What does it stand for?

**Comment by jostrasser** [comment] 2020-09-19 17:41
> The Home hub plays no role there.

Ok, thanks for the information. 

> Not familiar with that (those?) abbreviation(s).  Asked my kid, but he doesn’t have a clue either.  What does it stand for?

Best regards, Johannes ;)

**Comment by ebaauw** [comment] 2020-09-19 17:43
> Best regards, Johannes ;)

That actually makes sense.  They need to update the urban slang dictionary ;-)

**Comment by jostrasser** [comment] 2020-09-19 17:46
> That actually makes sense.  They need to update the urban slang dictionary ;-)

😀

Thanks your support :)

**Closed** 2020-09-20 09:08 UTC
Labels: question

**Comment by jostrasser** [comment] 2020-09-22 12:10
Hi @ebaauw ,

I think my problem is a little be different that the bug which you mentioned. They are having networking issues which are visible in the debug logs... but I cannot see any similar problems.

Today I faced the issue again.
I pressed a button on a switch, and I saw the following in the homebridge log:

[9/22/2020, 1:28:30 PM] [Homebridge-Hue] Hue Dimmer KINDERZIMMER On: homekit button single press


...and that's all... no lights turn on.


After restarting the homebridge i saw:

[9/22/2020, 1:30:10 PM] [Homebridge-Hue] Hue Dimmer KINDERZIMMER On: homekit button single press

[9/22/2020, 1:30:10 PM] [Homebridge-Hue] Kinderzimmer Decke1: homekit on changed from 0 to 1

[9/22/2020, 1:30:10 PM] [Homebridge-Hue] Kinderzimmer Decke2: homekit on changed from 0 to 1

...and all lights turns on.

It is really strange but I cannot find the root cause for the problem.
Controlling lights via the Apple Home App are working every time.
I only can see issues with all my switches... and when I am facing the problem NO switch is working... they are all affected at the same time.

Infrastructure:
iOS devices --> Homebridge --> Hue Bridge
Hue Bridge is not configured as Bridge in Apple Homekit, only Homebridge.

Do you have any ideas?

Thanks JO!

**Comment by ebaauw** [comment] 2020-09-22 15:36
When controlling the lights directly, your iOS device sends a command to Homebridge directly.  When pressing a button, Homebridge pushes an event to connected devices.  Your iOS device bumps the tile corresponding to the button.  Your Home hub executes the corresponding action, which involves sending a command to Homebridge.  Your symptoms indicate that the connection between your Home hub and homebridge fails, causing no command being sent to Homebridge.  This is unrelated to homebridge-hue.  Not sure if it’s caused by Homebridge 1.2.x, by tvOS14, or by the combination of both.

**Comment by jostrasser** [comment] 2020-09-22 17:39
> When controlling the lights directly, your iOS device sends a command to Homebridge directly.  When pressing a button, Homebridge pushes an event to connected devices.  Your iOS device bumps the tile corresponding to the button.  Your Home hub executes the corresponding action, which involves sending a command to Homebridge.  Your symptoms indicate that the connection between your Home hub and homebridge fails, causing no command being sent to Homebridge.  This is unrelated to homebridge-hue.  Not sure if it’s caused by Homebridge 1.2.x, by tvOS14, or by the combination of both.

Thanks for clarification... it was not clear for me before.
I will report this to the homebridge community.

BR Johannes!

**Comment by cappadanna** [comment] 2020-09-22 17:45
I have the exact same problem. Some of my IKEA and Aqara switches registers the button presses in both the Homebridge log and in the Apple Home app. But the lights they're supposed to control don't respond (actions assigned to the buttons in HomeKit) . They do If I use turn them on or off via the home app. I've been using ios14 beta on both my iPhone and my AppleTV since the first beta and everything has worked great. About a week ago I updated Homebridge to 1.2.0 (now trying 1.2.3) aswell as Homebridge hue to v0.11.76 and after that I started having this problem. If I restart Homebridge it works for a few hours but then the problems will start again (will try restarting my appletv hub next time). I suspect it must be a Homebridge issue. Have you found anything @jostrasser ?

**Comment by jostrasser** [comment] 2020-09-22 17:58
> I have the exact same problem. Some of my IKEA and Aqara switches registers the button presses in both the Homebridge log and in the Apple Home app. But the lights they're supposed to control don't respond (actions assigned to the buttons in HomeKit) . They do If I use turn them on or off via the home app. I've been using ios14 beta on both my iPhone and my AppleTV since the first beta and everything has worked great. About a week ago I updated Homebridge to 1.2.0 (now trying 1.2.3) aswell as Homebridge hue to v0.11.76 and after that I started having this problem. If I restart Homebridge it works for a few hours but then the problems will start again (will try restarting my appletv hub next time). I suspect it must be a Homebridge issue. Have you found anything @jostrasser ? 

Hi @cappadanna 

Your situation looks identical. I am running every few hours into the same issue.

I am using iOS14 / tvOS14 since BETA3 without issues.
The issue occurred for the first time after installing iOS14/tvOS14 GA-Release and updating homebridge to 1.2.x. I have done this at the same time, that's the reason why it is hard for me to find the root cause :(

I am facing the issue also with homebridge 1.2.3! (updated yesterday)
From the homebridge-hue perspective I cannot find any difference between versions. I can confirm that the issue is not related to any homebridge-hue version.

As workaround the following procedures are working for me:
1) restarting homebridge (100% confirmed)
2) restarting my AppleTVs (seems to me that this also is resolving the issue, not confirmed now, I have to test this again)

Please keep me posted when you have tested the ATV-restart.

Thanks JO!

**Comment by jostrasser** [comment] 2020-09-22 18:56
Resuming issue at []https://github.com/homebridge/homebridge/issues/2681

**Comment by martonky** [comment] 2020-09-26 12:34
I have the same problem what has @cappadanna.

**Comment by NaouTi080** [comment] 2020-12-04 16:37
I have the same problem ..
