### ISSUE TITLE
Battery unknown

### ISSUE THREAD

**Issue by ebrger** [ebaauw/homebridge-hue#223] opened 2017-12-03 22:24 UTC
Hue Motion Sensor shows "unknown battery status". Its of 0%, aktiv: yes; loading: no.
V. 0.5.48.
Is it a bug? Motions reaction works.
Thanks for help!

**Comment by ebaauw** [comment] 2017-12-04 07:03
What app?  Could you post a screenshot?  What does the Hue bridge report?  Could you attach a dump of the bridge state (see **Troubleshooting** in the README)?

**Comment by CooperCGN** [comment] 2017-12-07 15:07
I have the same problem since that last fix for the sensor problem, every app shows it, when I take out the batteries and put them in again the error disappears. 
![aecaa149-f864-4a76-9508-f85f94c11f93](https://user-images.githubusercontent.com/29116509/33721726-26936a04-db68-11e7-9ff4-ec22ed54be93.jpeg)

**Comment by ebaauw** [comment] 2017-12-07 18:23
> It happens after I restart Homebridge.

That would suggest an issue with homebridge-hue, but I cannot reproduce this.  Could you attach the output of `homebridge -D`?

> when I take out the batteries and put them in again the error disappears.

That would suggest an issue with deCONZ.  What does the Phoscon app report for battery status?  
deCONZ should setup attribute reporting for battery percentage, so that the motion sensor reports its battery percentage every 2 hours.  I suspect the sensor will report its battery status spontaneously when the batteries are re-inserted.  Does the battery percentage in HomeKit get updated 2 hours after starting homebridge?

**Comment by ebaauw** [comment] 2017-12-07 19:21
Did find a bug that `Charging` is set to _Not Charging_ instead of _Not Chargeable_.  Apple's Home app shows both as _Charging: No_, but Eve shows the difference.

**Comment by CooperCGN** [comment] 2017-12-07 21:39
I need to wait then till it happens again, right now it’s working.

**Comment by ebaauw** [comment] 2017-12-16 19:01
Closing this for now - please re-open if it happens again.

**Closed by ebaauw** 2017-12-16 19:01 UTC
