### ISSUE TITLE
Version 0.5.39

### ISSUE THREAD

**Issue by det-box** [ebaauw/homebridge-hue#185] opened 2017-10-21 12:38 UTC
Hi,
have a small bug with start
`Okt 21 14:32:43 hbridge homebridge[6422]: [2017-10-21 14:32:43] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^6.11.4 which does not satisfy the current Node version of v8.7.0. You may need to upgrade your installation of Node.
Okt 21 14:32:44 hbridge homebridge[6422]: [2017-10-21 14:32:44] Loaded plugin: homebridge-hue`

Thanks

**Comment by ebaauw** [comment] 2017-10-21 12:50
Is it just a message or does homebridge-hue not work?

**Comment by det-box** [comment] 2017-10-21 13:35
If it is only the message, it works fine.

**Comment by Nastra888** [comment] 2017-10-21 14:38
With me the Homebridge runs no longer after the update, I get this error:

`Okt 21 16:37:03 server homebridge[12110]: [2017-10-21 16:37:03] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^6.11.4 which does not satisfy the current Node version of v8.4.0. You may need to upgrade your installation of Node.`

and this

`Okt 21 16:37:08 server homebridge[12110]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257
Okt 21 16:37:08 server homebridge[12110]:       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
Okt 21 16:37:08 server homebridge[12110]:       ^
Okt 21 16:37:08 server homebridge[12110]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 70f58b55-e251-43e2-8f82-02b0346bba81
Okt 21 16:37:08 server homebridge[12110]:     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
Okt 21 16:37:08 server homebridge[12110]:     at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:350:18)
Okt 21 16:37:08 server homebridge[12110]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:8)
Okt 21 16:37:08 server homebridge[12110]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Okt 21 16:37:08 server homebridge[12110]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Okt 21 16:37:08 server homebridge[12110]:     at Module._compile (module.js:573:30)
Okt 21 16:37:08 server homebridge[12110]:     at Object.Module._extensions..js (module.js:584:10)
Okt 21 16:37:08 server homebridge[12110]:     at Module.load (module.js:507:32)
Okt 21 16:37:08 server homebridge[12110]:     at tryModuleLoad (module.js:470:12)
Okt 21 16:37:08 server homebridge[12110]:     at Function.Module._load (module.js:462:3)
Okt 21 16:37:08 server homebridge[12110]:     at Function.Module.runMain (module.js:609:10)
Okt 21 16:37:08 server homebridge[12110]:     at startup (bootstrap_node.js:158:16)
Okt 21 16:37:08 server homebridge[12110]:     at bootstrap_node.js:598:3
`

**Comment by Nastra888** [comment] 2017-10-21 14:38
I have node 8.4.0

**Comment by ebaauw** [comment] 2017-10-21 15:37
I strongly recommend using node v6.11.4 LTS, but if you insist on using v8, best upgrade to the latest v8.7.0.  I'll suppress the first message (which is actually issued by homebridge itself, based on the contents of homebridge-hue's package.json) in the next version of homebridge-hue, but will still issue a warning message when not using v6.11.4 LTS.

I don't think the second error is related to the first message.

> Okt 21 16:37:08 server homebridge[12110]: at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:350:18)

Nor to homebridge-hue.  It looks like the error is thrown while homebridge is restoring an accessory from `~/.homebridge/accessories/cachedAccessories`.  This only happens for accessories exposed by plugins using dynamic platform accessories - homebridge-hue doesn't.

Please attach (don't copy/paste) your full config.json and log output of `homebridge -D > log 2>&1`.

**Comment by Nastra888** [comment] 2017-10-21 15:48
I have reinstalled Homebridge and hue, now everything is re-running.

The problem is some plugins require at least node 7.x.x

Node I would like Updaten get there from 8.5.0 unfortunately this error:

https://github.com/agnat/node_mdns/pull/200

Have not found a solution for the node problem, but is it not your Problem .-)

Thank you for the fast answer

**Comment by det-box** [comment] 2017-10-21 17:00
I use the latest version 8. 7. 0 it up in the LOG.
I suspect this is the problem,
Node version of ^ 6th 11. 4
the ^ is determined false

**Comment by det-box** [comment] 2017-10-21 17:06
Oh,
 I see is fixed.
it works again
can be closed

Thank you

**Comment by ebaauw** [comment] 2017-10-21 17:17
Yes, fixed in v0.5.40.  package.json now specifies `engines.node` as `"^6.11.4 || ^8.7.0"`, so homebridge will accept any v6 >= 6.11.4 and any v8 >= 8.7.0.  homebridge-hue issues a warning when the version differs from 6.11.4, which I use to develop and test homebridge-hue.

**Closed by ebaauw** 2017-10-21 17:17 UTC
