### ISSUE TITLE
Delay in lights since using this plugin

### ISSUE THREAD

**Issue by danemacmillan** [ebaauw/homebridge-hue#53] opened 2017-01-22 19:08 UTC
I installed this plugin to expose Hue motion sensors to HomeKit. I've got 21 lights, 8 tap switches, and 1 motion sensor. Since installing, every tap switch press is consistently delayed by a second or two. The motion sensor also triggers on a delay similar to this; for example, without the plugin, the motion sensor triggers some lights on the first step on the stairs; having the plugin enabled will delay the trigger of lights until the fourth or fifth step is reached.

Without the plugin a tap switch press reacts instantly, and the motion sensor is triggered by the first step on the stairs. Upon re-enabling the plugin, the delays return.

My configuration:

```
     {
        platform: Hue,
        name: Hue,
        host: "",
        users: {
          [redacted]: [redacted]
        },
        heartrate: 2,
        timeout: 5,
        lights: false,
        philipslights: false,
        ct: false,
        groups: false,
        group0: false,
        rooms: false,
        sensors: true,
        excludeSensorTypes: [CLIP, ZLLLightLevel, Daylight, ZLLSwitch, ZGPSwitch],
        schedules: false,
        rules: false
      }
```

Is there something that could be affecting the performance of the officially-supported HomeKit accessories?

**Comment by ebaauw** [comment] 2017-01-23 22:15
> Without the plugin a tap switch press reacts instantly, and the motion sensor is triggered by the first step on the stairs. Upon re-enabling the plugin, the delays return.

Do I understand correctly that you turn on/off your lights with the Hue Motion sensor or Hue Tap switch using rules on the Hue bridge?  And when you just run homebridge-hue, not interacting with any HomeKit apps, the lights consistently respond with a 2-second delay?

> My configuration:

This is not part of a config.json file - the double quotes are missing.  Ignoring that, this configuration would only expose the Hue motion sensor's presence sensor and temperature sensor to HomeKit.  From that I assume you don't (yet) use any HomeKit triggers to control your lights from the Hue tap switches - just rules on the Hue bridge.

> Is there something that could be affecting the performance of the officially-supported HomeKit accessories?

What do you mean by "officially-supported HomeKit accessories?"  The only officially (by Philips and Apple) supported HomeKit devices on Hue are the Philips lights.

The lights, motion sensor, and tap switches are connected to the Hue bridge over the Zigbee network.  Like any Hue app, homebridge-hue connects to the Hue bridge over the IP network.  It cannot interfere in the communication between the Hue bridge and the devices.  As far as I can tell, the only possibilities for this communication to be delayed are:
1. Somehow, the bridge is so completely swamped with requests, that it cannot handle the Zigbee communication and/or execution of rules in time.
2. Somehow the Zigbee network is disrupted.

To figure out what's happening, could you please, while running homebridge-hue, disconnect the network cable from your Hue bridge and check whether the lights now react normally (without delay) to the tap switches.  If so, it would seem that the bridge was swamped (1); if not it would seem that the Zigbee network is disrupted (2).

Ad 1. Homebridge-hue requests the full bridge state every 2 seconds (or whatever `heartrate` is set to), but even a generation-1 (round) Hue bridge should be able to handle this load.  What happens when you increase the heartrate?  Please double check that homebridge-hue is the only application interacting with your Hue bridge - no HomeKit apps, no HomeKit triggers, no Hue apps, no MeetHue portal, no IFTTT.  Please attach the full debug output of `homebridge -D` and the full bridge state, so I can check if there's anything weird in your Hue bridge configuration (see **Troubleshooting** in the README how to do this).

Ad 2. Do you connect the server running homebridge-hue to the Hue bridge over WiFi?  Is it physically close to the Hue bridge, interfering with the Zigbee signal?  Try putting some distance between them, try moving to the 5 GHz WiFi band or to a wired connection, try Zigbee channel 25 (which doesn't overlap with the 2.4 GHz WiFi frequencies).

**Comment by danemacmillan** [comment] 2017-01-24 21:04
Thanks for the thorough reply.

> Do I understand correctly that you turn on/off your lights with the Hue Motion sensor or Hue Tap switch using rules on the Hue bridge? And when you just run homebridge-hue, not interacting with any HomeKit apps, the lights consistently respond with a 2-second delay?

Yes, the rules exist on the bridge. They've been programmed using the `iConnectHue` app on `iOS`. Yes, running the plugin seems to introduce a delay to the programmed rules on the bridge.

> This is not part of a config.json file - the double quotes are missing.

I don't know what this means.

> [T]his configuration would only expose the Hue motion sensor's presence sensor and temperature sensor to HomeKit. From that I assume you don't (yet) use any HomeKit triggers to control your lights from the Hue tap switches - just rules on the Hue bridge.

Yes, that's correct. None of the Tap switches are programmed to run HomeKit triggers, as they're "Not Supported" in Apple's Home app. I am also not using the sensor to run any HomeKit triggers.

> What do you mean by "officially-supported HomeKit accessories?" The only officially (by Philips and Apple) supported HomeKit devices on Hue are the Philips lights.

I mean precisely that. HomeKit officially supports Philips Hue bulbs and lightstrips. I'm asking whether the newly exposed motion and temperature sensor could be, in some way, having an adverse affect on the performance of bulbs and lightstrips, as the sensors are not officially supported. Could they be interacting with the official ones in an unorthodox or less than optimal way?

> [C]ould you please, while running homebridge-hue, disconnect the network cable from your Hue bridge and check whether the lights now react normally (without delay) to the tap switches.

The delay is gone when disconnected.

> Ad 1. Homebridge-hue requests the full bridge state every 2 seconds (or whatever heartrate is set to), but even a generation-1 (round) Hue bridge should be able to handle this load. What happens when you increase the heartrate?

I increased it to the default of `5`, and the delay was also gone--mostly. Only once did it seem to get caught up, as though I pressed the tap switch at the same time that `heartrate` was querying state information.

> Output of `homebridge -D |grep hue`:

```
[1/24/2017, 3:43:25 PM] Loaded plugin: homebridge-hue                                                                
[1/24/2017, 3:43:25 PM] Registering platform 'homebridge-hue.Hue'                                                      
[1/24/2017, 3:43:25 PM] [Hue] homebridge-hue v0.1.14, node v7.4.0, homebridge v2.1                                     
[1/24/2017, 3:43:25 PM] [Hue] contacting meethue portal                                                                
[1/24/2017, 3:43:25 PM] [Hue] meethue portal: no bridges registered
```

> Ad 2. Do you connect the server running homebridge-hue to the Hue bridge over WiFi?

No, it's connected via Ethernet to a tri-band AC5300 Wifi router. I use 5GHz almost exclusively. I do beam a 2.4GHz in a small part of the house for an old phone.

I think based on all this, it's probably just my Hue Bridge supporting a lot of rules Rules (54.0% capacity), Sensors (90.6%), and Schedules (18.0%). Those use statistics are from `iConnectHue`'s breakdown. I use that app a lot, and have created a lot of Tap rules, as it provides a tonne of granularity, so it's probably just that a `heartrate` of `2` is too heavy for my bridge's configuration.

I'm going to revert to the default `heartrate` and see how it performs over the next few days.

Based on all this, I'd say the issue has been resolved.

Thanks again!

**Comment by danemacmillan** [comment] 2017-01-24 21:23
Since running through the debug steps, I noticed that the plugin no longer finds a registered bridge:

```
[Hue] meethue portal: no bridges registered
```

That is causing HomeBridge to crash, so none of the plugins work. I've removed the plugin for now to get the others supported again.

**Comment by ebaauw** [comment] 2017-01-24 22:39
Odd, homebridge shouldn't crash in case homebridge-hue cannot find any bridges.  It should just start without any accessories for the Hue platform.
The Hue bridge should register itself with the meethue portal.  If it doesn't (no internet connection or you disabled portal services on the bridge) you can specify the bridge ip address in config.json.

**Comment by ebaauw** [comment] 2017-01-24 23:25
> I think based on all this, it's probably just my Hue Bridge supporting a lot of rules Rules (54.0% capacity), Sensors (90.6%), and Schedules (18.0%). Those use statistics are from iConnectHue's breakdown. I use that app a lot, and have created a lot of Tap rules, as it provides a tonne of granularity, so it's probably just that a heartrate of 2 is too heavy for my bridge's configuration.

It would seem so.  I am surprised homebridge-hue is able to affect bridge performance this badly by itself.  I have more rules on my 2nd version (square) bridge.  The 1st version (round) bridge is significantly less powerful, though.  Which version do you have?
I know of iConnectHue, but don't use it myself.  I think it also polls the bridge?  On how many devices are you running it?

I've been moving back and forth polling the full bridge state vs polling each resource type, lights, groups, sensors, schedules, rules, separately.  As the 1st gen bridge cannot handle too many requests in parallel, I now again retrieve the full bridge state.  This is quite some overkill if you only want to expose sensors, especially with many bridge rules.

**Comment by danemacmillan** [comment] 2017-01-26 08:10
This is the output when the `homebridge-hue` plugin config is added:

```
root@://danub ~/.homebridge # homebridge -D                                                                            *** 
WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.                              
*** WARNING *** Please fix your application to use the native API of Avahi!                                            
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>                        *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.                                                                    *** WARNING *** Please fix your application to use the native API of Avahi!                                            *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>  
[1/26/2017, 3:05:40 AM] Loaded plugin: homebridge-alarmdotcom                                                          
[1/26/2017, 3:05:40 AM] Registering platform 'homebridge-alarmdotcom.Alarmdotcom'                                      
[1/26/2017, 3:05:40 AM] ---                                                                                            
[1/26/2017, 3:05:40 AM] Loaded plugin: homebridge-hue                                                                  
[1/26/2017, 3:05:40 AM] Registering platform 'homebridge-hue.Hue'                                                      
[1/26/2017, 3:05:40 AM] ---                                                                                            
[1/26/2017, 3:05:40 AM] Loaded plugin: homebridge-people                                                               
[1/26/2017, 3:05:40 AM] Registering platform 'homebridge-people.People'                                                
[1/26/2017, 3:05:40 AM] Registering accessory 'homebridge-people.PeopleAccessory'                                      
[1/26/2017, 3:05:40 AM] Registering accessory 'homebridge-people.PeopleAllAccessory'                                   
[1/26/2017, 3:05:40 AM] ---                                                                                            
[1/26/2017, 3:05:40 AM] Loaded plugin: homebridge-sonos                                                                
[1/26/2017, 3:05:40 AM] Registering accessory 'homebridge-sonos.Sonos'                                                 
[1/26/2017, 3:05:40 AM] ---                                                                                            
[1/26/2017, 3:05:40 AM] Loaded config.json with 1 accessories and 3 platforms.                                         
[1/26/2017, 3:05:40 AM] ---                                                                                            
[1/26/2017, 3:05:40 AM] Loading 3 platforms...                                                                         
[1/26/2017, 3:05:40 AM] [Entrance alarm] Initializing Alarmdotcom platform...                                          
[1/26/2017, 3:05:40 AM] [Hue] Initializing Hue platform...                                                             
[1/26/2017, 3:05:40 AM] [Hue] homebridge-hue v0.1.14, node v7.4.0, homebridge v2.1                                     
[1/26/2017, 3:05:40 AM] [Hue] contacting meethue portal                                                                
[1/26/2017, 3:05:40 AM] Initializing People platform...                                                                
[1/26/2017, 3:05:40 AM] Initializing platform accessory 'Dane is home'...                                              
[1/26/2017, 3:05:40 AM] Initializing platform accessory 'Anyone'...                                                    
[1/26/2017, 3:05:40 AM] Initializing platform accessory 'No One'...                                                    
[1/26/2017, 3:05:40 AM] WebHook: Started server on port '51828'.                                                       
[1/26/2017, 3:05:40 AM] Loading 1 accessories...                                                                       
[1/26/2017, 3:05:40 AM] [Living Room Playbar] Initializing Sonos accessory...                                          
[1/26/2017, 3:05:40 AM] [Living Room Playbar] Found device at 192.168.1.202                                            
[1/26/2017, 3:05:41 AM] [Living Room Playbar] Found a playable coordinator device at 192.168.1.202 in zone 'Living Room' for accessory 'Living Room Playbar' in accessory room 'Living Room'                                                  
[1/26/2017, 3:05:41 AM] [Hue] meethue portal: no bridges registered                                                                                                                                                            
[1/26/2017, 3:05:44 AM] [Entrance alarm] Initializing platform accessory 'Alarm.com Entrance alarm'...
```

This is the output when the `homebridge-hue` plugin config is removed:
```
root@://danub ~/.homebridge # homebridge -D                                                                            *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.                              
*** WARNING *** Please fix your application to use the native API of Avahi!                                            
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>                        
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.                                                                    
*** WARNING *** Please fix your application to use the native API of Avahi!                                            
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>   
[1/26/2017, 3:10:58 AM] Loaded plugin: homebridge-alarmdotcom                                                          
[1/26/2017, 3:10:58 AM] Registering platform 'homebridge-alarmdotcom.Alarmdotcom'                                      
[1/26/2017, 3:10:58 AM] ---                                                                                            
[1/26/2017, 3:10:58 AM] Loaded plugin: homebridge-hue                                                                  
[1/26/2017, 3:10:58 AM] Registering platform 'homebridge-hue.Hue'                                                      
[1/26/2017, 3:10:58 AM] ---                                                                                            
[1/26/2017, 3:10:58 AM] Loaded plugin: homebridge-people                                                               
[1/26/2017, 3:10:58 AM] Registering platform 'homebridge-people.People'                                                
[1/26/2017, 3:10:58 AM] Registering accessory 'homebridge-people.PeopleAccessory'                                      
[1/26/2017, 3:10:58 AM] Registering accessory 'homebridge-people.PeopleAllAccessory'                                   
[1/26/2017, 3:10:58 AM] ---                                                                                            
[1/26/2017, 3:10:59 AM] Loaded plugin: homebridge-sonos                                                                
[1/26/2017, 3:10:59 AM] Registering accessory 'homebridge-sonos.Sonos'                                                 
[1/26/2017, 3:10:59 AM] ---                                                                                            
[1/26/2017, 3:10:59 AM] Loaded config.json with 1 accessories and 2 platforms.                                         
[1/26/2017, 3:10:59 AM] ---                                                                                            
[1/26/2017, 3:10:59 AM] Loading 2 platforms...                                                                         
[1/26/2017, 3:10:59 AM] [Entrance alarm] Initializing Alarmdotcom platform...                                          
[1/26/2017, 3:10:59 AM] Initializing People platform...                                                                
[1/26/2017, 3:10:59 AM] Initializing platform accessory 'Dane is home'...                                              
[1/26/2017, 3:10:59 AM] Initializing platform accessory 'Evita is home'...                                             
[1/26/2017, 3:10:59 AM] Initializing platform accessory 'Anyone'...                                                    
[1/26/2017, 3:10:59 AM] Initializing platform accessory 'No One'...                                                    
[1/26/2017, 3:10:59 AM] WebHook: Started server on port '51828'.                                                       
[1/26/2017, 3:10:59 AM] Loading 1 accessories...                                                                       
[1/26/2017, 3:10:59 AM] [Living Room Playbar] Initializing Sonos accessory...                                          
[1/26/2017, 3:10:59 AM] [Living Room Playbar] Found device at 192.168.1.202                                            
[1/26/2017, 3:10:59 AM] [Living Room Playbar] Found a playable coordinator device at 192.168.1.202 in zone 'Living Room' for accessory 'Living Room Playbar' in accessory room 'Living Room'                                                                                                                                                   
[1/26/2017, 3:11:03 AM] [Entrance alarm] Initializing platform accessory 'Alarm.com Entrance alarm'...                 
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:                                                                                                                                                                  
┌────────────┐                                                                                                         │ 
032-42-152 │                                                                                                         
└────────────┘                                                                                                                                                                                                                            
[1/26/2017, 3:11:03 AM] Homebridge is running on port 51826.
```

The first one never starts the server, so all my homebridge devices are unreachable in the Home app.

**Comment by danemacmillan** [comment] 2017-01-26 08:19
Interestingly, I just explicitly passed a local `host` IP address, being the one that belongs to the Hue Bridge, and the `[Hue] meethue portal: no bridges registered` error has gone and my Hue accessories appear.

**Comment by ebaauw** [comment] 2017-01-26 18:48
> The first one never starts the server, so all my homebridge devices are unreachable in the Home app.

Ah, homebridge doesn't crash, but simply hangs.  Odd, in my experience homebridge would timeout and proceed anyway, when a platform plug-in doens't answer the question which accessories it has.  This behaviour is actually better, because HomeKit would delete the homebridge-hue accessories once it finds that homebridge no longer provides them, forcing you to re-configure the room assignments, scenes, and triggers.  At least now, you can correct the situation without losing your HomeKit configuration.

> Interestingly, I just explicitly passed a local host IP address, being the one that belongs to the Hue Bridge, and the [Hue] meethue portal: no bridges registered error has gone and my Hue accessories appear.

By design: homebridge-hue doesn't query the meethue portal when host is specified in config.json.

**Closed** 2017-02-07 19:49 UTC
