### ISSUE TITLE
After deconz 2.05.74 / 2.05.75 Update unknown device

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#635] opened 2020-02-26 17:28 UTC
I have displayed an unknown device since the update to the new deconz beta. It masquerades as conbee 2 in the config.

Also the homebridge does not start anymore.
Never changi a running system 🙄🙄

I have displayed an unknown device since the update to the new deconz beta. It masquerades as conbee 2 in the config.

Also the homebridge does not start anymore.

![09B8DD89-6675-4712-A826-AC2E13EFA58F](https://user-images.githubusercontent.com/27686185/75370280-245b8280-58c5-11ea-8ec4-4d0da76e606e.jpeg)
![688179CE-5A31-4A30-B704-F1F86F34D2AC](https://user-images.githubusercontent.com/27686185/75370289-2887a000-58c5-11ea-8607-018b05ec0309.jpeg)

Never change a running system 🙄🙄🙄
You got any ideas?

**Comment by Nastras** [comment] 2020-02-26 17:33
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4257253/homebridge-hue.json.gz)

**Comment by Nastras** [comment] 2020-02-26 17:37
Ok I just checked the GUI and found out that it is really the coordinator (ConBee II) that is displayed.

**Comment by ebaauw** [comment] 2020-02-26 18:11
This is caused by https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2490.  Possible workarounds:
- Revert to deCONZ v2.05.73;
- Compile the REST API plugin from my latest PR;
- Blacklist the `/lights/19` resource.

**Comment by Nastras** [comment] 2020-02-26 18:21
Thanks for the quick answer!

I take every bug with me 🤕

I'd like to try option two. Can you tell me where the file (light_node.cpp) I need to exchange is located?

**Comment by ebaauw** [comment] 2020-02-26 18:30
It’s already been merged into the dresden repository.

**Comment by Nastras** [comment] 2020-02-26 18:39
I have now uninstalled and reinstalled deconz. For a short time it looked like the bug was fixed. Now it is back again.

What exactly do I have to do to get the merge?

**Comment by ebaauw** [comment] 2020-02-26 18:44
Compile the rest api plugin, see the README.  The change has been merged into the repository, but that doesn’t automagically update any released version.

**Comment by Nastras** [comment] 2020-02-26 19:27
I didn't know there was a feature for that. I have now done it and the bug is fixed.

Cool that you fixed it so quickly. Good Job Mr. @ebaauw 👍👍👍
Again a big thank you to you😉❗️

**Comment by zladukas** [comment] 2020-02-26 20:38
Strange, but after couple unsuccessful tries, homebridge has started on third try.
Blacklisted corresponding raspbee "light", just for sure.

**Comment by Nastras** [comment] 2020-03-09 07:51
After the update to deCONZ 2.5.75 I removed the coordinator from the blacklist because I thought the bug was fixed.

Now I just had to find out that the coordinator has registered again as light with a new name. 
It is also displayed again in various hue apps.
Is that right? 


"19": {
      "etag": "1faeb559532039704e1bff2ff248c24c",
      "hascolor": false,
      "manufacturername": "dresden elektronik",
      "modelid": "ConBee II",
      "name": "Configuration tool 19",
      "state": {
        "reachable": true
      },
      "swversion": "0x264a0700",
      "type": "Configuration tool",
      "uniqueid": "00:21:2e:ff:ff:04:86:94-01"
    },

**Comment by Nastras** [comment] 2020-03-09 07:58
Addition: homebridge-hue has not crashed so far due to this .-)))

**Closed** 2020-03-09 18:22 UTC

**Comment by ebaauw** [comment] 2020-03-09 18:59
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2534.
