### ISSUE TITLE
Crash when renaming Item

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-hue#826] opened 2020-11-23 08:19 UTC
After the upgrade to v0.12.2 my Awning (was called "Markise") was renamed to "Power 36". So I renamed it to "Markise" again in the Home App. It worked, but Homebrige quitted. Started again w/o daemon and tried again to catch the log:

```
[23/11/2020, 09:15:57] [Hue] Markise: homekit name changed from Markise to Markise Test
[23/11/2020, 09:15:57] [Hue] Markise: homekit name changed from Markise to Markise Test
[23/11/2020, 09:15:57] [Hue] Markise: homekit name changed from Markise to Markise Test
(node:27228) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:2818:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27228) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:2818:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[23/11/2020, 09:15:58] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:2807:12)
    at ConfiguredName.emit (events.js:327:22)
    at ConfiguredName.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at ConfiguredName.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1439:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1281:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[23/11/2020, 09:15:58] Got SIGTERM, shutting down Homebridge...
[23/11/2020, 09:15:58] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:2807:12)
    at ConfiguredName.emit (events.js:327:22)
    at ConfiguredName.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at ConfiguredName.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1439:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1281:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[23/11/2020, 09:16:03] [Hue] goodbye
```

**Comment by ebaauw** [comment] 2020-11-23 09:14
That doesn't look good.  Could you please enable debug mode in Homebridge (or start manually using `homebridge -D`), reproduce the error, and capture the log, incl. the debug messages?

**Comment by jan666** [comment] 2020-11-23 09:35
Its a Ubisys J1. I checked my question ticked in the deconz repo (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3147#issuecomment-674661062): 1x light + 3x sensor

**Comment by ebaauw** [comment] 2020-11-23 10:36
It’s a confirmed bug.  The different resources are exposed in one combined service.  They share the same _Configured Name_ characteristic, but each have a separate listener for the `set` event to update the `name` of the resource.  So Homebridge (or rather HAP-NodeJS) receives multiple callbacks for the `set` event.

**Comment by ebaauw** [comment] 2020-11-23 21:38
Fixed in v0.12.3.

**Comment by iantait** [comment] 2020-12-08 15:30
I believe I'm getting the same error 
`Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.`
To the best of my knowledge, I haven't renamed anything recently, or added anything, other than adding and removing homebridge-camera-ffmpeg.

Any thoughts on how I might debug this?
Thanks!

**Comment by ebaauw** [comment] 2020-12-08 15:35
Which version of Homebridge Hue are you on?

**Comment by iantait** [comment] 2020-12-08 15:39
homebridge-hue v0.12.10

________________________________

**Comment by ebaauw** [comment] 2020-12-08 15:50
Hm, that version should be OK.  Please attach the log, or al least the full message, including the stack trace.

Would be great if you can turn on debug mode and reproduce the error.

**Comment by iantait** [comment] 2020-12-08 16:02
This any good?:

`[12/8/2020, 3:45:10 PM] [Hue] Motion Sensor Hue Outdoors: set homekit temperature from 3.6°C to 3.5°C
[12/8/2020, 3:45:39 PM] Received warning for the plugin 'homebridge-hue' from the characteristic 'Configured Name': Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[Configured Name@Homebridge 6C5E] Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[12/8/2020, 3:45:39 PM] Received warning for the plugin 'homebridge-hue' from the characteristic 'Configured Name': Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[Configured Name@Homebridge 6C5E] Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[12/8/2020, 3:45:40 PM] Received warning for the plugin 'homebridge-hue' from the characteristic 'Configured Name': Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[Configured Name@Homebridge 6C5E] Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[12/8/2020, 3:45:40 PM] Received warning for the plugin 'homebridge-hue' from the characteristic 'Configured Name': Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[Configured Name@Homebridge 6C5E] Unhandled error thrown inside write handler for characteristic: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2825:12)
    at ConfiguredName.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1526:16
    at new Promise (<anonymous>)
    at ConfiguredName.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1524:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:121:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
[12/8/2020, 3:46:03 PM] [Hue] VPIR M: set homekit motion from 0 to 1`

**Comment by ebaauw** [comment] 2020-12-08 19:02
That should do, thanks.

What version of Homebridge are you running?

**Comment by iantait** [comment] 2020-12-08 19:05
homebridge-hue v0.12.10

**Comment by ebaauw** [comment] 2020-12-08 19:09
Yes, you've mentioned that before.  I asked for the Homebridge version.

**Comment by iantait** [comment] 2020-12-08 21:00
Oops 🙂

Was on 1.2.4 and I tried the latest beta.  I've just gone back to 1.2.3, and haven't seen it happen just yet.

I'll keep you posted.  Thanks!



________________________________

**Comment by iantait** [comment] 2020-12-09 11:22
Haven't seen this happen on 1.2.3 so far

**Comment by iantait** [comment] 2020-12-09 14:28
Spoke too soon :-)  Just added a new hue bulb, restarted homebridge, get that error, and homebridge restarts - seems to be in a loop of that currently.

**Comment by iantait** [comment] 2020-12-09 16:33
So I added a log in HueSensor.js at line 2825 (where its logged above):

```
HueSensor.prototype.setName = function (name, callback) {
  if (this.service === this.accessory.lightService) {
    callback = () => {}
  }
  if (name === this.hk.name) {

    this.log.info(
      '%s: ', this.hk.name
    )

    return callback()
  }
```

And it always outputs the name of one of my 4 Mi Magic Cubes - 'Red Room Cube' in the dump below:

I've removed one of them, and it broke at another of them.
I've since renamed them all - they all used to be called 'Mi Magic Cube Bedroom 1', 'Mi Magic Cube Bedroom 2' etc
Now all the names are significantly different, but it still occurs:

```
(node:38622) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2842:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/9/2020, 4:28:05 PM] [Hue] Red Room Cube: 
[12/9/2020, 4:28:05 PM] [Hue] Red Room Cube: 
[12/9/2020, 4:28:05 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at HueSensor.setName (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:2831:12)
    at ConfiguredName.emit (events.js:327:22)
    at ConfiguredName.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at ConfiguredName.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
[12/9/2020, 4:28:05 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by ebaauw** [comment] 2020-12-09 17:17
The Cube makes sense, in that it uses different clusters for the digital vs the analogue (turn) events.  However, I cannot reproduce the issue on my cube. Where did you change the name?  In the Home app or in deCONZ (Phoscon or another API client)?

**Comment by iantait** [comment] 2020-12-09 17:25
Phoscon
After the last couple of homebridge restarts - its kept going - I'll keep watching the logs :-)
Thanks!

**Comment by ebaauw** [comment] 2020-12-09 17:36
Thanks, managed to reproduce, but not consistently.  I do know where to look now, though.

**Comment by ebaauw** [comment] 2020-12-09 20:58
@iantait Could you please try beta v0.12.11-0?

**Comment by iantait** [comment] 2020-12-10 09:21
I've installed that version - looks good, thanks.

I've also restored a deconz backup that had the 4 cubes with similar names  - all starting with 'Mi Magic Cube' and the room name tagged on the end, to see if that made any odds.  Restarted homebridge several times, no issues.

Thanks again!

**Closed** 2020-12-15 18:50 UTC
Labels: bug
