### ISSUE TITLE
HomeKit supports programmable switch accessories with iOS 10.3 (beta)

### ISSUE THREAD

**Issue by jojost1** [ebaauw/homebridge-hue#54] opened 2017-01-26 14:48 UTC
Possible enhancement.
Could this new functionality be useful for homebridge-hue and the Hue Tap / Dimmer Switch?

**Comment by ebaauw** [comment] 2017-01-26 18:36
I surely hope so.  I don't have a spare iOS device to test the beta version, but as the Tap / Dimmer switch work with other HomeKit apps, I expect them to work with iOS 10.3 Home app as well.  I'll keep you posted.

**Comment by ebaauw** [comment] 2017-01-27 00:22
Hmm, Home handles the `Programmable Switch` services quite different from other HomeKit apps.  Playing with the HomeKit Accessory Simulator, I find:

- The tile has a new symbol and no longer shows _Not Supported_.  The tile behaves like a sensor; it's read-only - nothing happens when you press it;
-  When you hold the tile and select _Details_, Home shows two actions, _Single Press_ and _Double Press_, where you can select scenes and accessories, like with _Automation_ rules.  Note that you need a Home Hub (Gen4 AppleTV or iPad) to configure the actions;
- After configuring the actions, nothing shows in _Automation_, but rules show in other HomeKit apps (and in iOS 10.2 Home);
- The _Single Press_ rule is triggered by the (read-only) `Programmable Switch Event` characteristic becoming 0, the _Double Press_ by the event becoming 1;
- When adding multiple `Programmable Switch` services to a single accessory, they show up as multiple buttons under a single tile.  A single accessory with a `Motion Sensor` and a `Light Sensor` service still shows as two tiles.  This is what you'd want, but brilliantly confusing, as the tile sometimes refers to an accessory instead of a service.  Incidentally, iOS 10.2 Home also shows a single (_Not Supported_) tile for an accessory with multiple `Programmable Switch` services;
- Home only uses the read-only `Programmable Switch Event` characteristic, not the read/write `Programmable Switch Output State`.  Effectively, it handles a `Stateful Programmable Switch` service as a `Stateless Programmable Switch` service.

Obviously, this is a beta version of iOS 10.3 and things might change in the final release.  My preliminary conclusions, though:

- I would change homebridge-hue to expose the Hue Tap switch as a single accessory with four `Stateless Programmable Switch` services: _Button 1_, _Button 2_, _Button 3_ and _Button 4_.  I don't think _Double Press_ can work reliably, due to polling the Hue bridge, so I'd only support _Single Press_;
- I would change homebridge-hue to expose the Hue Dimmer switch as a single accessory with four `Stateless Programmable Switch` services: _On_, _Dim Up_, _Dim Down_, _Off_.  The _Single Press_ would be triggered on release (after press); the _Double Press_ on (release after) hold;
- Note to self:  I need to check if setting the `Programmable Switch Event` characteristic to 0 while it's 0 will actually trigger the rule;
- I would change homebridge-hue to expose CLIPGenericStatus and Daylight sensors and the bridge's heartbeat as another (likely custom) service/characteristic than `Stateful Programmable Switch` and `Programmable Switch Output State`.

**Comment by jojost1** [comment] 2017-01-27 08:54
Cool, that sure is an enhancement when 10.3 releases! 👍 
Thanks for looking into it.

**Comment by ebaauw** [comment] 2017-02-05 10:47
> Note to self: I need to check if setting the Programmable Switch Event characteristic to 0 while it's 0 will actually trigger the rule

It won't (yet?), see https://github.com/KhaosT/HAP-NodeJS/issues/134.

**Comment by ebaauw** [comment] 2017-02-07 20:05
> When you hold the tile and select Details, Home shows two actions, Single Press and Double Press, where you can select scenes and accessories, like with Automation rules. Note that you need a Home Hub (Gen4 AppleTV or iPad) to configure the actions;
The Single Press rule is triggered by the (read-only) Programmable Switch Event characteristic becoming 0, the Double Press by the event becoming 1;

Changing the `maxValue` property of the `ProgrammableSwitchEvent` characteristic shows more actions.  Value 2 corresponds to _Long Press_; values above 2 are labelled _(Unknown)_.  Setting `maxValue` to 0 removes the _Double Press_ button, leaving only _Single Press_.  Setting `allowedValues` to `[0, 2]` shows _Single Press_ and _Long Press_.

The Hue tap switch will be exposed as a programmable switch with four buttons, each with only a _Single Press_ action; the Hue dimmer switch will be a programmable switch with four buttons, each with _Single Press_ and _Long Press_ actions for Press vs Hold.

**Comment by ebaauw** [comment] 2017-02-08 17:16
> Home only uses the read-only `ProgrammableSwitchEvent` characteristic, not the read/write `ProgrammableSwitchOutputState`. Effectively, it handles a `StatefulProgrammableSwitch` service as a `StatelessProgrammableSwitch` service.

iOS 10.3 beta 2 only supports the `StatelessProgrammableSwitch` service, a `Stateful Programmable Switch` service shows as _Not Supported_, just as in iOS 10.2 and earlier.

**Comment by ebaauw** [comment] 2017-02-13 21:16
Changed in v0.2.0.  I'll keep this issue open until iOS 10.3 is released, just in case.

**Comment by jojost1** [comment] 2017-02-13 22:06
You're doing amazing work with v0.2.0 and I saw your comments for Homebridge itself, awesome you're doing this. Thanks. (-:

**Comment by ebaauw** [comment] 2017-02-13 23:14
Hmm, just updated my server to homebridge-hue v0.2.0.  The iOS 10.3 beta 2 Home app seems to show the buttons on the programmable switches in random order, different for each switch.  I didn't see this while testing on my laptop using a test home (but that might have been on beta 1).  I do see the same random behaviour in my "production" home, with a programmable switch provided by the HomeKit Accessory Simulator, so I doubt this is related to homebridge-hue, homebridge or HAP-NodeJS.

It might be caused by some corruption in my HomeKit configuration - I haven't yet reset it.  It might simply be a bug in the iOS 10.3 beta 2.  Or it might be that the order need to be specified explicitly in some way I haven't discovered yet.

I would appreciate if some-one could test this on a fresh HomeKit installation.  Attached the setup of the HomeKit Accessory Simulator: [Virtual homebridge.hasaccessory.zip](https://github.com/ebaauw/homebridge-hue/files/772659/Virtual.homebridge.hasaccessory.zip)

**Comment by DJay1** [comment] 2017-02-15 08:39
Thanks for the Update. I can see the dimming switch in Apple Home App and configure the four buttons. But its not shown anymore in the Elgato Eve App. Is this correct this way? Thx.

**Comment by jojost1** [comment] 2017-02-15 10:02
@DJay1 Can you show us how the switch is displayed in the Home app? I'm kinda eager how the interface looks like.

**Comment by ebaauw** [comment] 2017-02-15 19:52
@Djay1, Elgato seem to have changed the way Eve handles programmable switches in v2.6.  Eve no longer shows these in the _Rooms_ view.  Note however, that the buttons can be selected when defining triggers for rules (under _Scenes_).  Additionally, the services show under _Siri Names_ when viewing an accessory (under _Settings_).

I'm not sure that I would be the one to answer whether this is correct.  The official HomeKit API reference doesn't even mention any programmable switch service.   For the corresponding characteristics it reads:

> `HMCharacteristicTypeInputEvent`
> The value for the programmable switch input event. The value is an int that can change based on the type of programmable switch. A binary programmable switch, with a value of 0 indicates OFF (and 1 indicates ON). For a slider programmable switch, this value indicates the level.
>
> `HMCharacteristicTypeOutputState`
> The value for the programmable switch output state. This value is to be used for presentation purposes. A binary programmable switch with value 1 can present a state of ON.

Clearly, iOS 10.3 Home uses these characteristics in a completely different way.  I had hoped that Elgato would do the same in Eve v2.6, but Apple doesn't seem to have shared the changed meaning.  Also note that iOS 10.3 is still in beta, so things might still change.  I did notice differences between beta 1 and beta 2.

We need a fifth service for the Hue tap and Hue dimmer switch, for the `LastUpdated`, `Enabled`, `Status Active`, and `Status Fault` characteristics. I kept the `StatefulProgrammableSwitch` service from homebridge-hue v0.1.x, but that might not have been the best idea.  I'll change it to a custom service, so the sensor's config shows in Eve.

**Comment by ebaauw** [comment] 2017-02-15 20:45
@jojost, here's some screenshots from my old iPhone 5 running iOS 10.3 beta 2.

Room view:
![img_0007](https://cloud.githubusercontent.com/assets/22179355/22994482/5c2c3cd8-f3c7-11e6-8b4f-a8e0a77fe476.PNG)

When pressing and holding the Kitchen Dimmer tile, the following appears:
![img_0008](https://cloud.githubusercontent.com/assets/22179355/22994558/a1ecbc34-f3c7-11e6-8bed-fe7554fd1660.PNG)

When pressing detail (in three shots, because the iPhone 5 screen is too small):
![img_0009](https://cloud.githubusercontent.com/assets/22179355/22994587/c11f6cdc-f3c7-11e6-8506-194c18dfa2cf.PNG)
![img_0010](https://cloud.githubusercontent.com/assets/22179355/22994595/c72796e0-f3c7-11e6-91e7-5bc95ff18b06.PNG)
![img_0011](https://cloud.githubusercontent.com/assets/22179355/22994601/cfc9a4b4-f3c7-11e6-9d3e-93903f712f8a.PNG)

When pressing Add
![img_0012](https://cloud.githubusercontent.com/assets/22179355/22994617/dd3b93fa-f3c7-11e6-9e74-14ab48482c9f.PNG)

**Comment by ebaauw** [comment] 2017-02-15 20:55
And here the screenshots from Eve v2.6 (using home bridge-hue v0.2.2):

Dimmer now shows in room:
![img_0018](https://cloud.githubusercontent.com/assets/22179355/22994908/ef23e04e-f3c8-11e6-976b-cc9cc01b3eb1.PNG)

Details (note the `StatelessProgrammableSwitch` services are missing):
![img_0014](https://cloud.githubusercontent.com/assets/22179355/22994918/f749919c-f3c8-11e6-8c60-277ae58a1f5f.PNG)

Accessories view (in two shots):
![img_0015](https://cloud.githubusercontent.com/assets/22179355/22994963/1bd32280-f3c9-11e6-9067-93f6699f8ea2.PNG)
![img_0016](https://cloud.githubusercontent.com/assets/22179355/22994965/1eb0e334-f3c9-11e6-8a11-4ae0b6a4be70.PNG)

Defining a trigger for a rule (use value = 0 for _Single Press_ and value 2 for _Long Press_):
![img_0017](https://cloud.githubusercontent.com/assets/22179355/22994989/3cd27ad0-f3c9-11e6-83d9-825c39c8caf7.PNG)

**Comment by jojost1** [comment] 2017-02-15 21:03
Thanks a lot for developing this plugin. This is the most active I ever seen a dev be ;-)

The iOS 10.3 Home app with switch looks really good! Can't wait to use that when it's all working.

**Comment by ZoneMR** [comment] 2017-02-20 22:36
It seems my automation rules are triggered the very first time a tap/dimmer button is pressed, but not on subsequent presses. Perhaps the hack of re-setting the value to -1 after a button press isn't working for me?

I'm running the latest released version of iOS and tvOS, not updating to the betas just yet.

**Comment by ebaauw** [comment] 2017-02-21 18:56
Odd.  I'm having trouble testing rules (my HomeKit configuration is becoming too large), but under iOS 10.3 beta 2, I see the button tile reacting to each press.  homebridge-hue v0.3.4.

Are you sure homebridge-hue sees each button action?  Due to polling, it might miss a few.  You should see log messages like:
>[2/21/2017, 7:51:12 PM] [Hue] Living Room Dimmer On: homekit button single press
[2/21/2017, 7:51:14 PM] [Hue] Living Room Dimmer On: homekit button single press
[2/21/2017, 7:51:16 PM] [Hue] Living Room Dimmer On: homekit button single press

**Comment by ebaauw** [comment] 2017-02-21 19:35
@ZoneMR, finally got to do some tests.  I'm seeing the same: The rule fires the first time after it's defined or enabled.  The button tile in Home on iOS 10.3 beta 2 continues to react to presses.  A restart of homebridge doesn't do help.

I'm afraid this is related to homebridge-hue.  I tried the same with a virtual dimmer exposed by the Homekit Accessory Simulator: the rules continue to be triggered.  Of course, I need to change between values 0 and 1, so I cannot simulate two consecutive _Single Press_ actions.

**Comment by ebaauw** [comment] 2017-02-21 22:48
As far as I can tell, the rule only triggers consistently when:
1. The `InputEvent` characteristic's value actually changes;
2. The old `InputEvent` value is allowed;
3. The new `InputEvent` value is allowed.

Emitting the characteristic `change` event instead of re-setting the value doesn't seem to make a difference.  Best I can do for now, is allow the value for _Long Press_ button and reset the button to that value.  Of course, this will show the _Long Press_ button in Home.  Even with a 20ms timeout, I see both _Long Press_ and _Single Press_ light up.

The tile in the iOS 10.3 Home app reacts when the `InputEvent` characteristic is set, regardless whether the value actually changes.  I would expect the rules to behave similar.  My AppleTV still runs tvOS 10.1.1 and I don't have an iPad to spare for iOS 10.3 beta, so it could be the case in Home Hub tvOS 10.2 or iOS 10.3.

**Comment by ZoneMR** [comment] 2017-02-21 22:48
Yup, I'm seeing multiple button press entries in the log, but automation rules do not respond.

I wonder if this has something to do with the rate at which the value is reset back to -1? ie. could there be some kind of value debouncing happening when HomeKit processes automation rules?

In the absence of another solution, perhaps it's worth manually emitting a change event as you suggested in HAP-NodeJS/issues/134, with this of course being a temporary hack to tide us over until the new switch type is properly supported in HAP-NodeJS?

I miss my switches working! ;)

**Comment by ZoneMR** [comment] 2017-02-21 22:50
Our posts just crossed paths. Interesting that emitting change event doesn't work. I wonder how Apple officially expects these types of switches to behave.

Would allowing -1 as a value be a way forward? I presume it would show as an 'unknown' press, which may be less confusing than a Long Press?

**Comment by ebaauw** [comment] 2017-02-21 23:18
> Our posts just crossed paths
Indeed.

> Would allowing -1 as a value be a way forward? I presume it would show as an 'unknown' press, which may be less confusing than a Long Press?

Setting minValue to -1 causes no buttons to be displayed.  I could probably use 3 as an unknown button, though.  Haven't tried that yet.

> I wonder how Apple officially expects these types of switches to behave.

As do I.  I fear they won't share that info, except with MFI partners under strict NDA.

> I wonder if this has something to do with the rate at which the value is reset back to -1? ie. could there be some kind of value debouncing happening when HomeKit processes automation rules?

I tried a 500ms timeout instead of 20ms - no joy either.  Anyway, the tile reacts, so HomeKit is capable to seeing the change.

The only think I haven't tried yet is changing the allowed value after the button has been initialised (of course hoping the buttons won't change, but the allowed value for the rules do).

> I miss my switches working! ;)

I could restore the `OutputEvent` characteristic from v0.0.x.  Wouldn't be using a `StatelessProgrammableSwitch` service, but the custom service holding `Enabled`, `LastUpdated`, etc.  Although Eve v2.6 no longer seems to like `OutputEvent`...  Maybe use a custom characteristic `Button`?

**Comment by ebaauw** [comment] 2017-02-22 19:46
Just released v0.3.5.
- Allow value 3 for the button, to reset `InputEvent` to 3.  Shows as an _(Unknown)_ action in iOS 10.3 beta Home.  @ZoneMR please check if this works for you as well.
- Restored `OutputEvent` as a backup.  Eve shows it just fine, apparently it dislike is for the `StatelessProgrammableSwitch` service, not for the characteristic.

**Comment by ZoneMR** [comment] 2017-02-22 21:07
Thanks - that workaround will tide me over nicely until hopefully a neater solution arises as iOS 10.3 goes final :)

Works perfectly here with automation rules on InputEvent -> 0.

**Comment by ebaauw** [comment] 2017-02-28 17:25
The Home app in iOS 10.3 beta 4 still seems to show the buttons in random order.  if there is a trick to specifying the order (other than the order of the services), I cannot find it.

**Comment by gielk** [comment] 2017-03-01 16:53
@ebaauw How do u meen random order ? i have an hue tap and it shows 1,2,3,4 ?

**Comment by ebaauw** [comment] 2017-03-01 19:25
Yes, but typically those numbers don't relate to the corresponding buttons on the Hue tap, see #62.

**Comment by gielk** [comment] 2017-03-01 19:32
Aha now I get why it is not working. Thanks

**Comment by ZoneMR** [comment] 2017-03-05 10:53
I wonder if the ordering is truly random or linked to something like the service's UUID?

**Comment by ebaauw** [comment] 2017-03-05 11:50
I've been wondering the same.

The `UUID` property is the UUID of the service type, see [Service.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L36), so that's the same for all buttons.

Next I looked at the Instance ID `iid` property of the `Service` object.  However, this is assigned sequentially, see [IdentifierCache.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/model/IdentifierCache.js#L65). and `~/.homebridge/persist/IdentifierCache.XXXXXXXXXXXX.json`.

As far as I can tell, there's no other properties exposed to HomeBridge that could be used to indicate the order, see [toHAP()](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L196).

**Comment by sejoki** [comment] 2017-03-06 22:52
I kind of shot my entire home by upgrading to 10.3 on my old iPhone 5, so I thought to save it, I'd upgrade my SE to 10.3 as well (don't ask why I thought this would work, I was overtired...) So any ways, now I'm on 10.3 beta 4 and redid my home configuration.

When I try to configure the dimmer switch buttons, I get a "could not edit automation "…". Try again" error message, so it's not working for me at all. When I try adding it through eve, it tells me that it's not supported by home kit. Dash buttons that show up now have the same issue, so I guess it's not related to the hue plugin.
It's kind of curious that they call it "automation" though…

**Comment by ebaauw** [comment] 2017-03-06 23:27
I don't think I've seen that particular message, but in my experience HomeKit doesn't react well to configuration changes.  These are supposed to be sync'ed over iCloud, but that seems to fail when there's too many changes at once.  Is your AppleTV (or iPad) still listed as a connected Home Hub in the Home app?  Without a Hub, you cannot set any automation.

My best practice for reconfiguration is to:
- Disable iCloud Home on all my devices, except the iPad;
- Set up the iPad (temporarily) as Home Hub;
- Do all the changes on the iPad and check that the HomeKit rules work;
- (This is the hardest part) wait for the iPad to sync with iCloud.  I've no clue how to check that the sync is done, but 5 minutes or so seems enough;
- Re-enable iCloud Home on the other devices, one by one.

**Comment by ooii** [comment] 2017-03-09 14:46
Hi, is there any change with beta 5?

**Comment by ebaauw** [comment] 2017-03-09 18:59
No, buttons still assigned in random order.

**Comment by ooii** [comment] 2017-03-14 09:31
And with beta6? :)

**Comment by ooii** [comment] 2017-03-14 16:13
Hi,

Is it normal that, under 10.2, my Input Event list of Eve is empty while I have several dimmers?
As you can see, it does not seem empty in the Types view list:
![Type view](https://snag.gy/CSjarv.jpg)

But it is:
![Type view](https://snag.gy/ePVbMO.jpg)

**Comment by ebaauw** [comment] 2017-03-14 18:37
> And with beta6? :)

No joy.

> Is it normal that, under 10.2, my Input Event list of Eve is empty while I have several dimmers?

I'm afraid, to understand Apple's definition of "normal", we have to wait for a version of the HomeKit Accessory Simulator, with support for programmable switches.  I hope they'll publish that shortly after Xcode 8.3 will be released, which should be when iOS 10.3 is released.

The HomeKit API reports the `Switch Event` characteristic's permissions as notify only (no read, no write), regardless of what is specified through HAP.  This almost makes sense: how would you read the state of a stateless switch?  Consequently (I think), Eve doesn't show the characteristic values under _Types_.  However, you can select them under  _Triggers_ when defining rules (see my earlier screenshot).  You cannot select them under _Conditions_ either.

**Comment by ooii** [comment] 2017-03-15 08:23
Thanks for the clarification.

**Comment by ebaauw** [comment] 2017-03-16 18:36
No joy in beta 7 either.

**Comment by ebaauw** [comment] 2017-03-27 18:05
iOS 10.3 and tvOS 10.2 released.

Display order of the button still seems random.  Can't wait for an update of the HomeKit Accessory Simulator.

I need to push a new release (v0.3.13) to test whether actions for programmable switch buttons trigger correctly.  For now, please continue to use `Output State` in your HomeKit rules.

**Comment by ebaauw** [comment] 2017-03-27 19:23
OK, the `Input Event` rules (actions from the buttons) seem to be executed correctly on my AppleTV with tvOS 10.2.  @jojost1, @ZoneMR, @ooii, please let me know if this works for you as well.

Technically, I reset the `Input Event` to `1` (which normally stands for _Double Press_, but is _not_ in the allowed values) and after `waitTimeSwitch` milliseconds to `0` (for _Single Press_) or `2` (for _Long Press_).  I use the (now) default value `100` for `waitTimeSwitch`.

**Comment by ZoneMR** [comment] 2017-03-27 19:29
Yes, seems to work correctly here - at least within the ~90% reliability that I'm seeing with HomeKit automations in general.

**Comment by ebaauw** [comment] 2017-03-27 19:34
> Yes, seems to work correctly here

Cool!  I'll keep this issue open, until we solved the order of the buttons.

> at least within the ~90% reliability that I'm seeing with HomeKit automations in general

LOL.  
If the switches appear less reliable than other automations, you might want to try some different values for `waitTimeSwitch`.

**Comment by ooii** [comment] 2017-03-27 19:54
> OK, the Input Event rules (actions from the buttons) seem to be executed correctly on my AppleTV with tvOS 10.2. @jojost1, @ZoneMR, @ooii, please let me know if this works for you as well.
How can you do it on your Apple TV?
> Technically, I reset the Input Event to 1 (which normally stands for Double Press, but is not in the allowed values) and after waitTimeSwitch milliseconds to 0 (for Single Press) or 2 (for Long Press). I use the (now) default value 100 for waitTimeSwitch.
Is there any explanation how to proceed? 
I tested assigning tasks to the different buttons and understood the randomness :)

One strange behavior (not related to your plugin): when you start a long press on a dimmer, it fires the action of the short press.

**Comment by ebaauw** [comment] 2017-03-27 20:35
> One strange behavior (not related to your plugin): when you start a long press on a dimmer, it fires the action of the short press.

Can you double-check in Eve that Home created the correct trigger: `Input Event = 2`?

**Comment by ebaauw** [comment] 2017-03-27 20:42
> How can you do it on your Apple TV?

The HomeKit rules execute on a Home Hub, not on your iPhone.  By logging in to your iCloud account on your gen-4 AppleTV, it works as Home Hub.  If you press the location error in the left upper corner of the _Home_ screen in the Home app, it lists the Home Hubs.

> I tested assigning tasks to the different buttons and understood the randomness :)

If you press the button on the switch, the corresponding button in Home lights up.  That way, you can map the physical buttons to the buttons displayed in Home.  Alternatively, create rules in Eve, using the `Input Event` type as value trigger (see screenshot in my earlier post).  Value 0 is _Single Press_, value 2 is _Long Press_.

**Comment by ooii** [comment] 2017-03-27 20:56
>> One strange behavior (not related to your plugin): when you start a long press on a dimmer, it fires the action of the short press.

> Can you double-check in Eve that Home created the correct trigger: Input Event = 2?

Yes, it did.
Note that initial setting was made with the Hue official app (only single press). When I long press a button, it first fires the action for the single press then it fires the action for the long press.
I had the same behavior when configuring that with a REST client according to Philips instructions.
>> How can you do it on your Apple TV?

> The HomeKit rules execute on a Home Hub, not on your iPhone. By logging in to your iCloud account on your gen-4 AppleTV, it works as Home Hub. If you press the location error in the left upper corner of the Home screen in the Home app, it lists the Home Hubs.

OK. I thought you had the ability to check directly on the Apple TV that it has been executed. 
>> I tested assigning tasks to the different buttons and understood the randomness :)

> If you press the button on the switch, the corresponding button in Home lights up. That way, you can map the physical buttons to the buttons displayed in Home. Alternatively, create rules in Eve, using the Input Event type as value trigger (see screenshot in my earlier post). Value 0 is Single Press, value 2 is Long Press.

Good to know. Thanks.

**Comment by ebaauw** [comment] 2017-03-27 21:34
> Note that initial setting was made with the Hue official app (only single press). When I long press a button, it first fires the action for the single press then it fires the action for the long press.
I had the same behavior when configuring that with a REST client according to Philips instructions.

The rules you create with the Hue app (or through the Hue API) are stored and executed on the Hue bridge, nothing to do with HomeKit.  So your first "it" is the Hue bridge, and your second "it" is the HomeKit Home Hub.  They both work quite differently.

The Hue bridge generates `buttonevent` x000 on (initial) press, x001 every second while holding, x002 for release after short press and x003 for release after hold (x indicates the button: 1 = On, 2 = DimUp, 3 = DimDown, 4 = Off).  So short pressing a button generates `buttonevent` x000 followed by x002.  Long pressing generates x000, a series of x0001s and a final x003.

As homebridge-hue needs to poll the Hue bridge, it won't see all the buttonevents.  Depending on the timing of the button press relative to the heartbeat, it might see x000, x002 or just x002 for short press.  For long press it might see 0x000, x0001, x0003 or x000, x003, or x001, x003 or just x0003.  If you start homebridge as `homebridge -D`, homebridge-hue issues a debug message for each `buttonevent` it sees.  
homebridge-hue sets `Input Event` to _Single Press_ on x002.  On x001 or x003, it sets `Input Event` to _Long Press_.  It ignores x000 and any x001 and x003 after a x001.

If you want the Hue bridge rules to fire at the same time as the HomeKit rules (within the heartrate obviously), you should _not_ use x000, but x002 for _Short Press_ and x001 for _Long Press_.

**Comment by ooii** [comment] 2017-03-27 21:39
What you say is very interesting and requires to read it again to be sure to understand how it works. Thank you very much for your explanation. 
>If you want the Hue bridge rules to fire at the same time as the HomeKit rules (within the heartrate obviously), you should not use x000, but x002 for Short Press and x001 for Long Press.

I'd like to have the contrary: long press does not fire the action associated to short press.

**Comment by ebaauw** [comment] 2017-03-27 22:17
> I'd like to have the contrary: long press does not fire the action associated to short press.

The action is not associated to a short press, but to a _press_ button event.  To the Hue bridge, a short press is two button events: _press_ (x000) and _short release_ (x002).  A long press is three or more button events: _press_ (x000), _hold_ (x001), and _long release_ (x003).  By design, a Hue bridge rule on a _press_ button event fires on a short press and on a long press.  If you want a rule that fires only on short press, you should use the _short release_ button event.

**Comment by ooii** [comment] 2017-03-28 08:23
Thanks again for your explanation. That was not clear to me.
>By design, a Hue bridge rule on a press button event fires on a short press and on a long press.
If I understand well, that means that there is a rule for a _press_ button in the Hue bridge and that this rule is fired following both short and long press. Right? If I'm right, is there anyway to modify the rule for a _press_ button and to set it for, let's say, nothing? Actually, I just need to have only one action achieved when I press longly one button.
Once again, thanks a lot for the time you spend on developing this plugin, understanding its functioning and trying to explain it to others.

**Comment by ooii** [comment] 2017-03-28 20:51
Hi,

Yesterday, right after 10.3 release, I tested one of my dimmers and long presses. Except the randomness issue and my misunderstanding of difference between button, short, and long presses, everything was fine.
Today, I was making some tests and I'm facing these issues:

1. I added one new dimmer and I'm not able to use it to anything. I configured the short press of the on button to fire a scenario and, even if I see the corresponding button on the Home app lighting up, the scenario is not fired. I tested it with lamps, switches, same behavior.
3. Second strange behavior: short press lights up any of the three possible buttons on the Home app on random basis. I don't think there is any major difference in my press duration that lead to such a different behavior.

**Comment by ooii** [comment] 2017-03-28 21:58
Made other tests and figured out that the problem seems to come from the combo iPhone/iPad/Apple TV. Sometimes, the rules are synced between devices, sometimes not. Sometimes the Apple TV shows that it is connected to Home and sometimes not. 
I'll make tests again tomorrow.

**Comment by ooii** [comment] 2017-03-29 07:57
Made tests this morning and I think the problem I had comes from the iPhone which rules are not synced with the rest. 
Rules set with the iPad are fine.

**Comment by KhaosT** [comment] 2017-04-16 22:30
Some update to this issue. I made changes to homebridge v0.4.18 (and underlying hap-nodejs v0.4.23) to properly support HomeKit's new(?) notification only characteristic. Now setting characteristic value with the same value (via setValue/updateValue) will trigger new notification being sent to iOS device which should properly trigger the automation rules. There is no need to reset the input event to a different value after the timeout.

If you are using homebridge and it's dynamic platform accessory caching, you may need to remove those programable switches from home and added it back again in order for some flags to be properly set. If it's not possible to remove and add back those accessories, you may be able to correct those settings by manually setting `eventOnlyCharacteristic` to true on InputEvent's characteristic object.

**Comment by ebaauw** [comment] 2017-04-16 23:42
Thanks, @KhaosT, I'll have a look at this tomorrow.  I'm still using static platform accessories, so no need to update the accessory cache.

**Comment by KhaosT** [comment] 2017-04-16 23:43
In that case I think just update both homebridge and hap-nodejs should give you new behavior automatically.

**Comment by ebaauw** [comment] 2017-04-16 23:54
@KhaosT did you already find a new version of the HomeKit Accessory Simulator that supports programmable switches?  I'm still having an issue that the order of the buttons presented by the iOS builtin Home app appears to be random, and doesn't match the order of the `StatelessProgrammableSwitch` services.

**Comment by KhaosT** [comment] 2017-04-17 00:01
@ebaauw try to add a service label index characteristic to programmable switch service? I haven't find a new simulator yet but saw this characteristic from metadata dump on iOS directly. Here is the characteristic definition.

```
"service-label-index": {
    "Format": "uint8",
    "MinValue": 1,
    "ShortUUID": "000000CB",
    "LocalizationKey": "",
    "DefaultDescription": "Label Index",
    "StepValue": 1,
    "Properties": 2,
    "MaxValue": 255
}
```

**Comment by ebaauw** [comment] 2017-04-17 00:19
That could be just what the doctor ordered.  Unfortunately HAS doesn't allow custom characteristics with a UUID in the Apple range, so I'll have to change my code to test this.

What is the `Properties` key?  How do I translate that to a Characteristic property?

**Comment by KhaosT** [comment] 2017-04-17 00:21
I think can actually solve your order issue. I manually patched HAS (by changing default.metadata.plist) and it's working fine. I'll publish those new services in hap-nodejs so you can just use it. Home app even allow programmable switch to define what button is labeled like (dot or number)

![img_0246](https://cloud.githubusercontent.com/assets/1725664/25075418/f87b7ede-22c8-11e7-9e99-c23aa745b8bd.PNG)

**Comment by KhaosT** [comment] 2017-04-17 00:37
Alright, hap-nodejs v0.4.24 along with homebridge v0.4.19 should have this. Try set `Characteristic.LabelIndex` on the `Stateless Programmable Switch Service` to the index of the button. And optionally add `Service.Label` to accessory to customize the button text. For detail of changes, please check https://github.com/KhaosT/HAP-NodeJS/commit/5090434e4b4f59f05ba2ab30089d2f54a365c724.

**Comment by ebaauw** [comment] 2017-04-17 10:40
Works like a charm!  Thanks again, @KhaosT.

I don't suppose there's a way to specify a custom label for the switch buttons, like `On`, `Dim Up`, `Dim Down`, `Off`?

I'd like to add the following lines to HAP-NodeJS/lib/gen/HomeKitTypes.js:
>   // The value property of ProgrammableSwitchEvent must be one of the following:
Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS = 0;
Characteristic.ProgrammableSwitchEvent.DOUBLE_PRESS = 1;
Characteristic.ProgrammableSwitchEvent.LONG_PRESS = 2;

I'm happy to create a pull request, but I fear the directory name `gen` means this file was generated?

**Comment by ebaauw** [comment] 2017-04-17 10:41
homebridge-hue v0.3.15 uses the `LabelIndex` and no longer resets the `InputEvent` value. @jojost1, @ZoneMR, @DJay79, @gielk, @ooii: can you please check if this version works for you as well?  Please make sure to update NodeJS, npm, and homebridge before updating homebridge-hue.

For now, I'll continue to provide `OutputState` in the custom service, next to the iOS 10.3 buttons, for those who still use HomeKit rules based on this characteristic.  It still resets the value when the same button is pressed two times in a row, and it still uses the config.json `waitTimeSwitch` for the delay.  I will remove these in a future version, once we've got confirmation that v0.3.15 works.

**Comment by jojost1** [comment] 2017-04-17 11:22
After some simple testing: it seems to work just fine! :-) @ebaauw

**Comment by ooii** [comment] 2017-04-17 13:13
Hi, buttons are now in the right order. Automation, however, still requires that the iOS app is working. Maybe I need to change some settings somewhere?
Thanks for the good work.

**Comment by ebaauw** [comment] 2017-04-17 13:19
> Automation, however, still requires that the iOS app is working. Maybe I need to change some settings somewhere?

Is that only for the button actions or for any HomeKit automation?

**Comment by ooii** [comment] 2017-04-17 15:04
Home automation, in my case, works only and perfectly with motion sensors when no Home app is on. With switches, even virtual, it does work only if the Home app is on.
So I'm not even sure that homebridge-hue plugin is concerned.

**Comment by ebaauw** [comment] 2017-04-17 19:52
Hm, I experienced that once: HomeKit rules would only fire when a HomeKit app was active.  I'm afraid that sounds like a broken HomeKit configuration (somehow the AppleTV doesn't connect directly to the accessory and needs a HomeKit app to sync the accessory state through iCloud).  Maybe signing out of and back into your iCloud account on the AppleTV helps.  I fixed it by deleting my Home from HomeKit and reconfiguring everything from scratch.  No fun.

**Comment by KhaosT** [comment] 2017-04-17 20:19
@ebaauw I don't think HomeKit allows custom labeling in Home app.

Technically that file is generated but I guess it's fine to submit a PR since HAS hasn't been updated to contain this change yet.

**Comment by ooii** [comment] 2017-04-18 08:00
> Maybe signing out of and back into your iCloud account on the AppleTV helps. 
Already tested with no success.
> I fixed it by deleting my Home from HomeKit and reconfiguring everything from scratch. No fun.
I thought about it but I'm afraid to reset all my setting (more than 100 accessories) with no guarantee to have it working. Thanks for the feedback.

One related question: when customising a room with a photo on one iOS device, is this photo supposed to appear on other iOS devices connected to the same account?

**Comment by KhaosT** [comment] 2017-04-18 08:00
@ooii nope.

**Comment by ooii** [comment] 2017-04-18 08:02
Thanks for the (very) fast answer :)

**Comment by ebaauw** [comment] 2017-04-20 20:14
Removed `Output State` characteristic for the Hue dimmer switch and Hue tap in v0.4.0, as iOS 10.3 programmable switches are now fully functional.  To create HomeKit rules for these, use the iOS built-in Home app, or define an automation trigger on `Input Event` using another HomeKit app.  The config.sys `waitTimeSwitch` key is also removed.

**Closed by ebaauw** 2017-04-20 20:14 UTC
Labels: enhancement
