### ISSUE TITLE
Aqara Relay Battery Status

### ISSUE THREAD

**Issue by KIBkz** [ebaauw/homebridge-hue#741] opened 2020-07-24 20:32 UTC
#### Issue
Aqara Relay show Battery Status (0% battery) in Homekit

**Comment by ebaauw** [comment] 2020-07-24 20:35
That’s probably because deCONZ reports `config.battery` with a value 0.  Please attach the debug dump file, so I can confirm.

**Comment by KIBkz** [comment] 2020-07-24 20:41
> That’s probably because deCONZ reports `config.battery` with a value 0. Please attach the debug dump file, so I can confirm.
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4974159/homebridge-hue.json.gz)

**Comment by ebaauw** [comment] 2020-07-25 11:09
Hm. there seem to be several things wrong with how these devices are exposed:
- The `manufacturername` is `null` on the `/lights` resource for endpoint 02;
- Both `/lights` resources use `type` `"Dimmable light"`, but don't expose `state.bri`.  I don't think the relays support dimming (_Level Control_ cluster), so the `type` should be corrected (assuming the device wrongly advertises this type on both endpoints).
- The `ZHAConsumption` and `ZHAPower` `/sensors` resources contain `config.battery` - I don't think these relays have a battery, do they?  The values, unsurprisingly, are `null`.

I assume the device does have two relays?  Otherwise, only one `/lights` resource should have been created.

These need to be fixed in deCONZ, I've re-opened https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2909.

**Comment by KIBkz** [comment] 2020-07-25 18:38
> Hm. there seem to be several things wrong with how these devices are exposed:
> 
>     * The `manufacturername` is `null` on the `/lights` resource for endpoint 02;
> 
>     * Both `/lights` resources use `type` `"Dimmable light"`, but don't expose `state.bri`.  I don't think the relays support dimming (_Level Control_ cluster), so the `type` should be corrected (assuming the device wrongly advertises this type on both endpoints).
> 
>     * The `ZHAConsumption` and `ZHAPower` `/sensors` resources contain `config.battery` - I don't think these relays have a battery, do they?  The values, unsurprisingly, are `null`.
> 
> 
> I assume the device does have two relays? Otherwise, only one `/lights` resource should have been created.
> 
> These need to be fixed in deCONZ, I've re-opened [dresden-elektronik/deconz-rest-plugin#2909](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2909).

Yes aqara relay have two relay .

**Closed** 2020-08-01 09:01 UTC
Labels: question
