### ISSUE TITLE
V.0.13.16 - Issues with Philips Hue Dimmer Switches

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#971] opened 2021-04-18 19:18 UTC
Hi,

Bug1:
The update today deletes all my Hue Dimmer Switch configs in Homekit for the Buttons 2 and 3! Only 1 and 4 keeps the config of scenes and lamps. 

Bug2:
"long press" isn't working anymore and is registered as "single press".

**Comment by ebaauw** [comment] 2021-04-18 19:43
I can reproduce bug 2: it looks like Homebridge Hue applies the `hueDimmerRepeat` setting, even when it hasn't been set.  The exposed actions (_Single Press_ and _Long Press_ (when not set) vs only _Single Press_ (when set) seem to be OK.

I'm not sure I understand bug 1.  Do you mean the actions for those buttons?  Did you define them on _Single Press_ or on _Long Press_?  Did you try different settings for `hueDimmerRepeat`?  I would expect the actions for _Long Press_ to be lost when setting `hueDimmerRepeat`, but the _Single Press_ actions shouldn't be affected.

**Comment by ebaauw** [comment] 2021-04-18 20:14
Damn, can reproduce bug 1 as well.  I create the _Stateless Programmable Switch_ services with subtype based on the button name, instead of the button index.  With the refactoring of the ZHASwitch handling, I renamed some of the buttons for consistency (e.g. from "Dim Up" to "DimUp"), not realising it would have any impact.  Changing the subtype to the index would delete all actions for all buttons on all switches, so let's not do that.  I'll see if I can undo the renaming.

**Comment by ebaauw** [comment] 2021-04-18 20:53
Fixed in v0.13.7.

Unfortunately, the actions will be removed again when upgrading from (now unpublished) v0.13.6 to v0.13.7, but will be preserved when upgrading from v0.13.5 to v0.13.7.

**Comment by jostrasser** [comment] 2021-04-19 03:58
> Damn, can reproduce bug 1 as well. I create the _Stateless Programmable Switch_ services with subtype based on the button name, instead of the button index. With the refactoring of the ZHASwitch handling, I renamed some of the buttons for consistency (e.g. from "Dim Up" to "DimUp"), not realising it would have any impact. Changing the subtype to the index would delete all actions for all buttons on all switches, so let's not do that. I'll see if I can undo the renaming.

Not funny if you have many dimmer switches ;)

>  can reproduce bug 2: it looks like Homebridge Hue applies the hueDimmerRepeat setting, even when it hasn't been set.

correct, I am not using `hueDimmerRepeat ` to be able to set a different scene on a long press.
example: `single press` = `heater on`, `long press` = `heater off`.

> Unfortunately, the actions will be removed again when upgrading from (now unpublished) v0.13.6 to v0.13.7, but will be preserved when upgrading from v0.13.5 to v0.13.7.

Thanks for the quick fix. Lets do the config again... ;)


Here my config if needed:

```
"name": "Homebridge-Hue",
            "anyOn": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "forceCt": true,
            "hueDimmerRepeat": false,
            "brightnessAdjustment": 100,
            "heartrate": 1,
            "timeout": 5,
            "parallelRequests": 4,
            "waitTimeResend": 100,
            "waitTimeUpdate": 20,
            "lowBattery": 25,
```

**Comment by jostrasser** [comment] 2021-04-19 04:22
@ebaauw 

done the config of some switches and found another bug:

Philips Hue Dimmer GEN2: unable to configure long press of button 2.
If I select a scene it will not be configured.
The config of GEN1 switches is working fine. Only GEN2 affected.

![image](https://user-images.githubusercontent.com/14274103/115181142-8bdf1d80-a0d7-11eb-91ea-af19e43e5ea2.png)

**Comment by ebaauw** [comment] 2021-04-19 06:15
I can set actions for the 2021 model allright.  From the screenshot, it looks like Homebridge Hue exposes the dimmer correctly.

Probably an issue with HomeKit syncing the config over iCloud.  Force-quit Home and wait a couple of minutes before trying again.  I assume you’re trying the same scene as on _Single Press_?  Otherwise double-check the scene.

**Comment by jostrasser** [comment] 2021-04-19 06:23
@ebaauw 

tested again... it is not Apple Home App related... tested with multiple devices.
Config is syncing really fast and without any issues with other switches, scenes and devices.

I have now selected a device and not a scene and can see the same issue.
The Long Press isn't usable on button 2 on GEN2.

**Comment by jostrasser** [comment] 2021-04-19 07:11
ok, found the issue:
While trying to assign different scenes I produced a conflict with rules.

I´ve now deleted/cleaned all rules of the button our of HomeKit and reassigned the scene, now it is working.

Thanks!

**Closed** 2021-04-24 10:35 UTC
Labels: bug
