### ISSUE TITLE
Gledopto RGBWW controller issue

### ISSUE THREAD

**Issue by KLucky13** [ebaauw/homebridge-hue#738] opened 2020-07-19 21:56 UTC
So I read through issue #571, and I'm not so advanced in this but it seems like the issue I am having. The homekit interface seems very glitchy when changing colors or changing the temperature of the white LED's. 

I'm using a GLEDOPTO RGBWW controller (type GL-C-008). I have set certain colors in different scenes with a certain intensity. When switching between scenes, only the intensity is changing and the color is remaining the same. I have no automations or scenes other than in homekit itself, so that's the big difference compared to the user in the linked issue. 

I'm not sure where to look for the problem and if the current new homekit version (in beta) already tackled this issue. I now installed this controller on 1 location in my house and wanted to expand to 5 more, but as long as this issue is not fixed, I'm not expanding. So I wanted to know if there is a fix to this issue or not. 

So I linked the GLEDOPTO controller through phoscon to my CONBEE II stick. It worked straight away and showed up in homebridge/homekit. Switching colors in scenes is the big issue here.

Any help?

**Comment by KLucky13** [comment] 2020-07-19 21:59
Maybe one thing to add: these GLEDOPTO controllers of this type do exist in 2 versions, one where the RGB and CW/CC functions are shown in 1 device (this is the one I have), and another version where the RGB is shown as 1 device and the CW/CC is shown as another one. I'm not sure but maybe that might be the way to go to get around this issue? I'm not sure.. In each case, it should work as well when shown as 1 device, which I prefer anyway to keep the amount of devices in homekit to a minimum

**Comment by ebaauw** [comment] 2020-07-20 05:22
Are you using Zigbee scenes or HomeKit scenes?  Could you please capture ant attach a debug log file, while recalling the scene?  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by KLucky13** [comment] 2020-07-21 15:11
> Are you using Zigbee scenes or HomeKit scenes? Could you please capture and attach a debug log file, while recalling the scene? See https://github.com/ebaauw/homebridge-hue#debug-log-file.

Hello, I will look into the dumpfile, I need to hook up a monitor to the Pi I assume, since it is tucked away in the basement without a screen or remote desktop. 

I did make this screenshot from the webapp while switching back and forth between the 2 scenes I was talking about. It shows a brightness and colorchange, however it is not changing to the color I'm expecting. Instead of going from cold white 100% to green LED 50% it is going to cold white 50%. It seems it is unable to jump from the white LED scheme to the RGB scheme or something? 

https://ibb.co/HN0MKwL

**Comment by ebaauw** [comment] 2020-07-21 15:15
Looks like you're (also?) setting colour temperature from the HomeKit scene?  What does the scene look like in Eve?

**Comment by KLucky13** [comment] 2020-07-21 15:22
> Looks like you're (also?) setting colour temperature from the HomeKit scene? What does the scene look like in Eve?

So I don't use the EVE app, I installed it to check and I found the issue I think. In the EVE app it is showing both a "temperature" and "color" change for the LED strip. When I turn of the temperature when it needs to switch to green en turn of the color when it needs to switch to bright cold white it works perfectly fine from EVE. However when I call the scene from homekit, it doesn't work? When changing scenes in Eve, can't homekit take this behavior over or do I need to do something special to let homekit take over the logic from what I programmed in EVE?

**Comment by KLucky13** [comment] 2020-07-21 15:29
> Looks like you're (also?) setting colour temperature from the HomeKit scene? What does the scene look like in Eve?

What do you mean exactly by "what does it look like"? You also have 2 tabs, one for color, one for temperature. When I set the scene, it works once, it jumps to green, but it does not jump back to the white leds once the other scene is called. It seems it has difficulties switching between the two "tabs" if that makes sense. It's almost like you can only use either one in your scenes or it gets messed up.

**Comment by KLucky13** [comment] 2020-07-21 15:30
I uploaded the dumpfile here: https://gofile.io/d/gYq45k

**Comment by KLucky13** [comment] 2020-07-21 15:45
> Looks like you're (also?) setting colour temperature from the HomeKit scene? What does the scene look like in Eve?

Sorry I closed the topic by accident, so I deleted the scenes and started over and only added the LED controller to make things a bit simpler. These is what I have for both scenes. One I'm asking bright White light, on the other one 50% colored. It works once, but once it is switched to either one of the (either the white leds or the RGB leds), it seems to be stuck in there.

https://ibb.co/wcgq2NB
https://ibb.co/VTMbgYK

**Comment by ebaauw** [comment] 2020-07-21 17:31
Please run `Homebridge -D` and capture and attach the log file, while recalling the scenes.

**Comment by ebaauw** [comment] 2020-07-21 17:38
> I uploaded the dumpfile here: https://gofile.io/d/gYq45k

You're running an old version of Homebridge Hue, please update to the latest version.  Notably v0.11.68 has some changes handling color temperature, which might be related to your issue.  You might be hitting some HomeKit limitations, that .68 and later work around.

**Comment by KLucky13** [comment] 2020-07-21 18:16
> > I uploaded the dumpfile here: https://gofile.io/d/gYq45k
> 
> You're running an old version of Homebridge Hue, please update to the latest version. Notably v0.11.68 has some changes handling color temperature, which might be related to your issue. You might be hitting some HomeKit limitations, that .68 and later work around.

Yes I know, I get this warning "The homebridge-hue plugin recommends running on Node.js v12.18.2 or later. You are currently running Node.js v12.16.2." So I don't want to update yet. Still need to figure out how to update the Node.js (still relativly new to all of this).

**Comment by KLucky13** [comment] 2020-07-21 18:19
> Please run `Homebridge -D` and capture and attach the log file, while recalling the scenes.

Please forgive me that I still don't know what I'm doing but I get this: 
https://ibb.co/5jbfVC9

**Comment by ebaauw** [comment] 2020-07-21 21:43
Damn, autocorrect like to capitalise `homebridge`.  It’s `homebridge -D`.

**Comment by KLucky13** [comment] 2020-07-21 22:02
> Damn, autocorrect likes to capitalise `homebridge`. It’s `homebridge -D`.

Oh ok thanks, now I get an error that the file is not found? 

https://ibb.co/BL6GbC0

**Comment by KLucky13** [comment] 2020-07-23 18:39
> Damn, autocorrect likes to capitalise `homebridge`. It’s `homebridge -D`.

Any idea what is causing that error?

**Comment by ebaauw** [comment] 2020-07-23 18:50
Too old version of Homebridge Hue in combination with newer version of Homebridge.

**Comment by KLucky13** [comment] 2020-07-23 19:32
> Too old version of Homebridge Hue in combination with newer version of Homebridge.

Thanks for the reply, I updated everything to the latest version as you can see here:
https://ibb.co/5LVmFzN

I retried and still got the same error message: 
https://ibb.co/Nm8cTmh

**Comment by ebaauw** [comment] 2020-07-23 21:50
You probably need to specify `-U /var/lib/homebridge` as well (assuming that's where your config.json is).

**Comment by KLucky13** [comment] 2020-07-27 10:02
> You probably need to specify `-U /var/lib/homebridge` as well (assuming that's where your config.json is).

I want to say thank you for the patience to get me through this issue since it's obvious I have no where near the knowledge compared to other users. So I tried that command, but also here it's throwing "command not found" error.

So sorry to ask again, but how and where do I need to specify that command? I really want to provide you with the log to solve this issue

**Comment by ebaauw** [comment] 2020-07-27 17:43
Try `homebridge -D -U /var/lib/homebridge > homebridge.log 2>&1`.  Make sure to stop any homebridge service first, or you’ll get the EADDRINUSE error.

**Comment by KLucky13** [comment] 2020-08-01 09:55
Hello, I'm sorry I had a very busy week, I will check it this weekend, the issue still exists so I will provide you with the log ASAP!

**Comment by KLucky13** [comment] 2020-08-01 18:14
Hello,

So I did what you asked. Do you need to specify the path everytime? I don't really know what the command "homebridge -D -U /var/lib/homebridge > homebridge.log 2>&1" does, but in each case If I don't specify the path it doesn't work, If I type in the command you suggested I get no errors so I assume the log is written. 

So in what order do I need to do what in order to provide you with what you need to have a look at what goes wrong here?

1) When do I need to run that command? 
- First try to switch the scenes a few times
- Shut down homebridge 
- Write log with the command you posted? Is this correct?
2) How do I find that log? 

![image](https://user-images.githubusercontent.com/16277786/89107697-20fb9280-d433-11ea-8ed1-918dfdd6a0a9.png)

**Comment by gborios** [comment] 2020-08-01 21:09
@KLucky13 Some of your controller channels may be fried. I have 2 of this model and mis-wired one. Now the RGB channels are still working fine but the 2 CCT channels are misbehaving: having both set at 50% they are both lit, but changing to cold or warm color, both are dropping to 0% instead of one dropping to 0% and the other raised to 100%.

I know this is a hardware issue for me because the second controller with the exact same setup works just fine.

Your symptoms look very much like my dead controller...

**Comment by KLucky13** [comment] 2020-08-01 21:15
> @KLucky13 Some of your controller channels may be fried. I have 2 of this model and mis-wired one. Now the RGB channels are still working fine but the 2 CCT channels are misbehaving: having both set at 50% they are both lit, but changing to cold or warm color, both are dropping to 0% instead of one dropping to 0% and the other raised to 100%.
> 
> 
> 
> I know this is a hardware issue for me because the second controller with the exact same setup works just fine.
> 
> 
> 
> Your symptoms look very much like my dead controller...

It does not sound like the same issue, it's a brand new controller without it ever being miswired. It also works perfectly fine when I manually control it. It's just when calling scenes that it does not do what I ask. If I manually ask whatever colour, it always does it as expected

**Comment by ebaauw** [comment] 2020-08-02 08:40
@KLucky13, I need a debug log from the moment homebridge starts to the moment the issue occurs.
- Stop any homebridge service;
- Start homebridge in debug mode, capturing the output into a file:
  ```
  sudo homebridge -D -U /var/lib/homebridge > homebridge.log 2>&1
  ```
- Try to switch scenes, reproducing the issue.
- Stop homebridge by hitting ctrl-C in the terminal where you issues the command.
- Check the `homebridge.log` contains the output.
- Compress the file by `gzip homebridge.log`.
- Attach the file `homebridge.log.gz` here.

**Comment by KLucky13** [comment] 2020-08-04 21:43
Ok so you saw the other topic where my entire HomeKit automation list was gone after a power failure. So in order for this test I needed to re-create the scenes as described as above. For some reason it seems to work.. the thing is, before the power failure I deleted the scenes and started over multiple times without it ever properly working. Now it works first time.. it both switches brightness AND colour when switching between scenes.. I'm very confused to be honest.. I will do some more tests tomorrow, I will expand the scenes with more lights and see if it keeps working or not.

**Comment by ebaauw** [comment] 2020-08-15 10:54
@KLucky13 did you manage to do the tests?  Are you still experiencing the issue?

**Comment by KLucky13** [comment] 2020-08-15 19:12
> @KLucky13 did you manage to do the tests? Are you still experiencing the issue?

Hi, so far so good. Pretty annoying since I still don't know what caused the problem in the first place.. I now created scenes with both the RGBWW lights and other lights and can switch between them as much as I want, the RGBWW switches both color and brightness as expected...

**Comment by ebaauw** [comment] 2020-08-15 19:14
OK, thanks.  Closing this issue then.

**Closed by ebaauw** 2020-08-15 19:14 UTC
Labels: question

**Comment by czm97176** [comment] 2020-08-16 06:39
HI, i am not sure is it a same issue.

i am using decoz as gateway. i am able to control the brightness & color on my iphone via Home App. 
However, changing the color temperatures is not working properly.  

The log is showing hue and color is changing when setting the color temperature
![image](https://user-images.githubusercontent.com/11693804/90328310-064a2180-dfce-11ea-91e7-07a0328b2850.png)

so it's not changing the color temperature. so i back to the Phoscon App to change the color temperature.
it;s works flawlessly. Would you please help to take a look?

![image](https://user-images.githubusercontent.com/11693804/90328346-4a3d2680-dfce-11ea-8d4f-5ad55c85df79.png)

**Comment by ebaauw** [comment] 2020-08-16 08:16
Not related.  Apple’s Home app doesn’t support colour temperature properly for color lights, use Eve instead.  See #571.
